name: jwt-django-app
app_id: da_nZyIPt1UZxma
owner: btrunk
package: .
env:
  DJANGO_DEBUG: 'False'
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_SECRET_KEY: O_2eY7mg2JOflMK1JFKvAxYhxtk8v6Q0_eRePgO7psErA6tnCPj6KEKNbqbgeNxrglc
cli_args:
- web
debug: true
kind: wasmer.io/App.v0
mysql_databases:
- name: jwt
https_only: true
