# Generated by Django 5.2.7 on 2025-11-01 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
            ],
        ),
    ]
